name: flutter_svg_icons
description: A package to show svg asset files in icon widgets, supporting responsive svg icons.
version: 0.0.2
repository: https://github.com/MohammedAsaadAsaad/flutter_svg_icons

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
